# this corresponds to the default config
train:
  dataset_path: NLBDataset:root=/valohai/inputs/data/object/
  batch_size_per_gpu: 200
  OFFICIAL_EPOCH_LENGTH: 1250
student:
  arch: vit_base
  block_chunks: 4
teacher:
  momentum_teacher: 0.992
  final_momentum_teacher: 1
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 30
optim:
  epochs: 100
  base_lr: 0.001  # learning rate for a batch size of 1024
  lr: 0.  # will be set after applying scaling rule
  min_lr: 1.0e-06
  warmup_epochs: 10
  scaling_rule: sqrt_wrt_800
crops:
  global_crops_scale:
  - 0.4
  - 1.0
  local_crops_number: 8
  local_crops_scale:
  - 0.25
  - 0.4
  global_crops_size: 224
  local_crops_size: 96
evaluation:
  eval_period_iterations: 10000