# this corresponds to the default config
train:
  dataset_path: NLBDataset:root=/valohai/inputs/data/object/
  batch_size_per_gpu: 200
student:
  arch: vit_base
  block_chunks: 4
optim:
  epochs: 50
  scaling_rule: sqrt_wrt_800
evaluation:
  eval_period_iterations: 5000
crops:
  global_crops_scale:
  - 0.4
  - 1.0
  local_crops_number: 12
  local_crops_scale:
  - 0.2
  - 0.7