# this corresponds to the default config
train:
  dataset_path: NLBDataset:root=/valohai/inputs/data/object/
  batch_size_per_gpu: 200
  OFFICIAL_EPOCH_LENGTH: 1250
student:
  arch: vit_base
  block_chunks: 4
  drop_path_rate: 0.4
teacher:
  momentum_teacher: 0.994
optim:
  epochs: 500
  weight_decay_end: 0.2
  base_lr: 2.0e-04  # learning rate for a batch size of 1024
  warmup_epochs: 80
  layerwise_decay: 1.0
  scaling_rule: sqrt_wrt_800
crops:
  global_crops_scale:
  - 0.4
  - 1.0
  local_crops_number: 8
  local_crops_scale:
  - 0.25
  - 0.4
  global_crops_size: 224
  local_crops_size: 96
evaluation:
  eval_period_iterations: 5000