# this corresponds to the default config
train:
  dataset_path: NLBDataset:root=/valohai/inputs/data/final_dataset_after_filtering_outliers/
  batch_size_per_gpu: 200
  OFFICIAL_EPOCH_LENGTH: 2200
student:
  arch: vit_base
  block_chunks: 4
optim:
  epochs: 100
  scaling_rule: sqrt_wrt_800
crops:
  global_crops_scale:
  - 0.4
  - 1.0
  local_crops_number: 8
  local_crops_scale:
  - 0.25
  - 0.4
  global_crops_size: 224
  local_crops_size: 96
evaluation:
  eval_period_iterations: 10000